{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hof-rds-api.fullname" . }}
  labels:
    {{- include "hof-rds-api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | quote }}
  {{- $externalSecretTarget := .Values.externalSecret.target | default dict }}
  {{- $targetCreationPolicy := $externalSecretTarget.creationPolicy | default "Owner" }}
  target:
    name: {{ include "hof-rds-api.runtimeSecretName" . }}
    creationPolicy: {{ $targetCreationPolicy | quote }}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
