apiVersion: v1
kind: Service
metadata:
  name: {{ include "hof-rds-api.serviceName" . }}
  labels:
    {{- include "hof-rds-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName | default "http" }}
  selector:
    {{- include "hof-rds-api.selectorLabels" . | nindent 4 }}
