name: Building, scanning, and pushing Docker images

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - CCL-*
        tags:
            - "v*"
            - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    build-scan-push:
        permissions:
            contents: read
            id-token: write
        uses: Home-Office-Digital/core-cloud-workflow-docker-actions/.github/workflows/build-scan-push.yml@1.5.0
        with:
            working_directory: "."
            dockerfile: "Dockerfile"
            image_name: "hof/hof-rds-api"
            # image_tag: "${{ github.event_name == 'pull_request' && format('pr-{0}-{1}', github.event.pull_request.number, github.event.pull_request.head.sha) || github.sha }}"
            image_tag: "${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.sha }}"
            # tag_latest: true
            tag_latest: ${{ github.event_name != 'pull_request' }}
        secrets:
            AWS_ECR_ACCOUNT_ID: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
            ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
            EXEMPTIONS_APP_ID: ${{ secrets.EXEMPTIONS_APP_ID }}
            EXEMPTIONS_APP_PRIVATE_KEY: ${{ secrets.EXEMPTIONS_APP_PRIVATE_KEY }}